---
title: "First_Draft"
author: "Oren"
date: "8/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading loads of libraries
library(tidyverse) 
library(tidycensus) 
library(tmap)
library(tmaptools) 
library(sf)
library(tigris)
library(httr)
library(jsonlite)
library(censusapi)
library(rgdal)
library(sp) 
library(leaflet) 
library(maptools)
library(rgdal)
library(geojsonR)
library(data.table)
library(purrr)
library(corrplot)
library(corrr)
library(RSQLite)
library(openintro)
```


```{r loading df}

df_pov <- fread("Data/School_Proficiency_Index.csv")
head(df_pov)

df_jobs <- fread("Data/Jobs_Proximity_Index.csv")
head(df_jobs)

df_lots <- fread("Data/Low_Transportation_Cost_Index.csv")
head(df_lots)

```

```{r downloading census_repeat of next}

# total_pop = "B01003_001",
# median_income = "B19013_001"

# Pop_ALL <- get_acs(
#   geography = "tract",
#   variables = "B01003_001",
#   state = state.abb,
#   year = 2016,
#   survey = "acs5",
#   geometry = TRUE, key = census_api_key
#   )

```

```{r}
# TIGER_DP

# Pop_ALL_ZIP_15 <- get_acs(
#   geography = "zcta",
#   variables = "B01003_001",
#   state = state.abb,
#   # year = 2015,
#   survey = "acs5",
#   # geometry = TRUE, 
#   key = census_api_key
#   )
# 
# 
# fwrite(Pop_ALL_ZIP_15, "pop_all_zip.csv")
```



```{r downloading geographical}
# For the codes - https://censusreporter.org/topics/table-codes/

#   geography = "zcta",

# us <- unique(fips_codes$state)[1:51]
Pop_ALL <- get_acs(
  geography = "tract",
  variables = "B01003_001",
  state = state.abb,
  # year = 2016,
  survey = "acs5",
  geometry = TRUE, key = census_api_key
  )

Inc_ALL <- get_acs(
  geography = "tract",
  variables = "B19013_001",
  state = state.abb,
  # year = 2016,
  survey = "acs5",
  geometry = TRUE, key = census_api_key
  )

```

```{r merging data}

df_pov <-  df_pov %>% # creating new df
  group_by(TRACT, COUNTY, STUSAB) %>% # grouping by location
  mutate(school_index = mean(schl_idx, na.rm=TRUE)) %>% # creating average of school index
  select(STATE, COUNTY, TRACT, STUSAB, school_index) %>% # Keeping columns I need
  distinct()

df_jobs <- df_jobs %>% 
  group_by(TRACT, COUNTY, STUSAB) %>% # grouping by location
  mutate(jobs_index = mean(jobs_idx, na.rm=TRUE)) %>% # creating average of jobs index
  select(STATE, COUNTY, TRACT, STUSAB, jobs_index) %>% # Keeping columns I need
  distinct()


df_lots <- df_lots %>% 
  group_by(TRACT, COUNTY, STUSAB) %>% # grouping by location
  mutate(poverty_index = mean(pov_idx, na.rm=TRUE), labor_index = mean(lbr_idx, na.rm=TRUE), hazard_index = mean(haz_idx, na.rm=TRUE), transportation_cost_index = mean(tcost_idx, na.rm=TRUE) , transport_index = mean(trans_idx, na.rm=TRUE)) %>% # creating averages of a bunch of columns
  select(STATE, COUNTY, TRACT, GEOID, STUSAB, poverty_index, labor_index, hazard_index, transportation_cost_index, transport_index) # Keeping what I need

# Change GEOID to character
df_lots$GEOID <- as.character(df_lots$GEOID)
# Adding 0 to beginning of short ones
df_lots$GEOID <- df_lots$GEOID %>% str_trunc(11) %>% str_pad(11, "left", pad = "0")


full_df <- df_lots %>% inner_join(df_pov) %>% inner_join(df_jobs)

```

```{r joining the data}
# sum(full_df$GEOID %in% Pop_ALL$GEOID)
colnames(Inc_ALL)[c(4,5)] <- c("income_estimate", "income_moe")
Inc_ALL <- as.data.frame(Inc_ALL)[ c(1, 2, 4, 5)]
colnames(Pop_ALL)[c(4,5)] <- c("population_estimate", "population_moe")

df_final <- inner_join(Inc_ALL, full_df)
df_final <- inner_join(Pop_ALL, df_final)

df_final <- df_final %>% filter(st_is_empty(geometry) == FALSE)

df_stats <- as.data.frame(df_final)[-c(6)]

colnames(df_final)

# Changing name to County Names
df_final$NAME <- sub(".*?, ", "", df_final$NAME)

df_final <- df_final %>% mutate(State_Name = abbr2state(STUSAB))

```


```{r some statistical analysis}

correlate(df_stats[c(4, 6, 12:18)])
boxplot(df_stats[12:18])
boxplot(df_stats[6])
boxplot(df_stats[4])

ggplot(df_final, aes(population_estimate)) + geom_density()
ggplot(df_final) + geom_qq(aes(sample=population_estimate))

ggplot(df_final, aes(income_estimate)) + geom_density()
ggplot(df_final) + geom_qq(aes(sample=income_estimate))


ggplot(df_final, aes(poverty_index)) + geom_density()
ggplot(df_final) + geom_qq(aes(sample=poverty_index))


ggplot(df_final,aes(poverty_index, school_index)) + geom_point(size = .00001, alpha = .1) + geom_smooth(method = lm)


summary(lm(school_index ~ population_estimate + income_estimate + poverty_index + transportation_cost_index + transport_index + jobs_index, data = df_final))

summary(lm(school_index ~ population_estimate + income_estimate + poverty_index + transportation_cost_index + transport_index + jobs_index, data = (df_final %>% filter(str_detect(STUSAB, State)))))


ggplot(df_final, aes(income_estimate, color = STUSAB)) + geom_density()
```



```{r mapping the data}
State = "CA"
Measurement = "income_estimate"

# Define the shape and the layer elements
# tmap_mode("view")
tm_shape(df_final %>% filter(str_detect(STUSAB, State))) +
  tm_polygons(Measurement, border.alpha = 0, id="NAME")

# tm_polygons("income_grp", palette="-Blues", contrast=.7, id="name", title="Income group") 

# + tm_borders(alpha = 0, lwd = 0)
```

