---
title: "Plotly_playing"
author: "Oren"
date: "8/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(plotly)
ay <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "second y axis"
)
fig <- plot_ly()
fig <- fig %>% add_lines(x = ~1:3, y = ~10*(1:3), name = "slope of 10")
fig <- fig %>% add_lines(x = ~2:4, y = ~1:3, name = "slope of 1", yaxis = "y2")
fig <- fig %>% layout(
    title = "Double Y Axis", yaxis2 = ay,
    xaxis = list(title="x")
  )

fig
```


```{r}
old.y <- list(
  side = "left",
  title = "Home"
)

new.y <- list(
  overlaying = "y",
  side = "right",
  title = "Rental"
)

plot_ly(zillow) %>%
  add_lines(x = ~Date, y = ~(select(Zipcode == "10016")[value_home]), yaxis="y1", name = "Home") %>%
  add_lines(x = ~Date, y = ~(select(Zipcode == "10016")[value_rental]), yaxis = "y2", name = "Rental") %>%

# plot_ly(zillow %>% filter(Zipcode == "10016")) %>%
#   add_lines(x = ~Date, y = ~value_home, yaxis="y1", name = "Home") %>%
#   add_lines(x = ~Date, y = ~value_rental, yaxis = "y2", name = "Rental") %>%  
#   
#     
  
# (zillow %>%  filter(City == "New York") %>% group_by(Date) %>%
#             summarise(value = mean(value_home, na.rm = T)))  %>%              
#   add_lines(x = ~Date, y = ~value, yaxis="y1", name = "Avg Home") %>%
 
  layout(yaxis2 = new.y, yaxis = old.y, xaxis = list(title="Own or Rent"))
```



```{r}
st_test <- "NY"
city_test <- "New York"
zip_test <- "10001"

test %>% filter(State == "NY") %>% filter(City == "New York") %>% group_by(Date) %>% summarise(mean(value_rental, na.rm = T))


zillow %>% 
            filter(City == "New York") %>% group_by(Date) %>%
            summarise(mean(value_home, na.rm = T))

```

```{r}
library(reprex)
reprex(input = test)
```


```{r}
df <- fread("df_final.csv")
fig <- plot_ly(df %>% filter(STUSAB == "AK"), x = ~poverty_index, y = ~labor_index, type = 'scatter')
fig

colnames(df)
df[12:18] <- lapply(df[12:18], as.numeric)

transform(df, school_index = as.integer(school_index))
transform(df, jobs_index = as.integer(jobs_index))
fit <- lm(poverty_index ~ labor_index, data = df %>% filter(STUSAB == "AK"))

df %>% filter(STUSAB == "AK") %>% 
  plot_ly(x = ~labor_index) %>% 
  add_markers(y = ~poverty_index) %>% 
  add_lines(x = ~labor_index, y = fitted(fit))


```

