---
title: "Starting_Off"
author: "Oren"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


https://www.zillow.com/research/data/

https://walker-data.com/tidycensus/

https://github.com/hrecht/censusapi

```{r}

#install.packages("")
library(httr)
library(jsonlite)

library(censusapi)
library(rgdal)
library(sp) 
library(leaflet) 
library(dplyr) 
library(ggplot2) 
library(maptools)
library(sf)
```

```{r}
df1 <- read.csv("Data/Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")
#summary(df1)
```


```{r}
df2 <- read.csv("Data/School_Proficiency_Index.csv")
head(df2)


df3 <- read.csv("Data/Residential_Construction_Permits_by_County.csv")
head(df3)



df4 <- read.csv("Data/Jobs_Proximity_Index.csv")
head(df4)



df5 <- read.csv("Data/Labor_Market_Engagement_Index.csv")
head(df5)



df6 <- read.csv("Data/Environmental_Health_Hazard_Index.csv")
head(df6)







df7 <- read.csv("Data/Small_Area_Fair_Market_Rents.csv")
head(df7)


df8 <- read.csv("Data/Low_Poverty_Index.csv")
head(df8)



df9 <- read.csv("Data/Low_Transportation_Cost_Index.csv")
head(df9)



df10 <- read.csv("Data/Labor_Market_Engagement_Index.csv")
head(df10)



df11 <- read.csv("Data/Environmental_Health_Hazard_Index.csv")
head(df11)
```



```{r}
as_Spatial(test$geometry)

us <- unique(fips_codes$state)[1:51]

totalpop <- map_df(us, function(x) {
  get_acs(geography = "tract", variables = "B01003_001", 
          state = x, key = census_api_key)
})

str(totalpop)

orange <- get_acs(state = 06, county = 059, geography = "tract", 
                  variables = "B19013_001", geometry = TRUE, key = census_api_key)

library(sf)
options(tigris_use_cache = TRUE)

totalpop_sf <- reduce(
  map(us, function(x) {
    get_acs(geography = "tract", variables = "B01003_001", 
            geometry = TRUE, key = census_api_key)
  }), 
  rbind
)

str(totalpop_sf)

data(fips_codes)

data(county_laea)

df5$GEOID<-as.character(df5$GEOID)


test <- df5 %>%
#  filter(variable == "B27001_001") %>% # much faster than using distinct()
  select(GEOID) %>%
  arrange(GEOID) 


test <- county_laea %>%
#    filter(variable == "B27001_001") %>% # much faster than using distinct()
  select(GEOID) %>%
  left_join(df5, by = "GEOID") %>%
  arrange(GEOID) 
test


#st_cast(test$geometry, to = "MULTIPOLYGON")
st_crs(test$geometry) <- test$geometry

tm_shape(test) +
  tm_polygons("lbr_idx")
```


```{r}
# my_states <- c("AL")

# my_vars <- c(
#   total_pop = "B01003_001",
#   median_income = "B19013_001"
#   )
# us[1:51]
Pop_ALL <- get_acs(
  geography = "tract",
  variables = "B01003_001",
  state = us,
  # year = 2016,
  survey = "acs5",
  geometry = TRUE, key = census_api_key #, options(tigris_use_cache = TRUE)
  )

# Pop_ALL <- Pop_AL
#, options(tigris_use_cache = TRUE)
```


```{r}
cast_all <- function(xg) {
  lapply(c("MULTIPOLYGON"), 
      function(x) st_cast(xg, x))
}
st_sfc(cast_all(test$geometry))
```

```{r}
na_check <- get_acs(geography = "tract",
                    state = "AL",
                    county = "Autauga County",
                    table = "B01001",
                    geometry = FALSE,
                    year = 2014,
                    survey = "acs5",
                    cache_table = TRUE,
                    keep_geo_vars = FALSE,
                    key = census_api_key)
```

```{r}
df5 %>% filter(STATE_NAME == "New Hampshire")
```



```{r}
ggtract<-fortify(df7, region = "GEOID") 
# join tabular data
ggtract<-left_join(ggtract, df7, by=c("GEOID")) 

# here we limit to the NYC counties
ggtract <- ggtract[grep("Kings|Bronx|New York County|Queens|Richmond", ggtract$geography),]

ggplot() +
  geom_polygon(data = ggtract , aes(x=long, y=lat, group = group, fill=percent), color="grey50") +
   scale_fill_gradientn(colours = c("red", "white", "cadetblue"),
                       values = c(1,0.5, .3, .2, .1, 0))+
  coord_map(xlim = c(-74.26, -73.71), ylim = c(40.49,40.92))
```



```{r}
apis <- listCensusApis()
View(apis)
```

```{r}
sahie_vars <- listCensusMetadata(
    name = "timeseries/healthins/sahie", 
    type = "variables")
head(sahie_vars)
```

```{r}

# Averaging some values since they include multiple versions
# df2 <- df2 %>% group_by(TRACT, COUNTY, STUSAB) %>% mutate(avg = mean(schl_idx, na.rm=TRUE)) %>% arrange(GEOID)
# df4 <- df4 %>% group_by(TRACT, COUNTY, STUSAB) %>% mutate(avg = mean(schl_idx, na.rm=TRUE)) %>% arrange(GEOID)
# df9 <- df9 %>% group_by(TRACT, COUNTY, STUSAB) %>% mutate(avg = mean(pov_idx, na.rm=TRUE)) %>% arrange(GEOID)




# Change GEOID to character
df_main$GEOID <- as.character(df_main$GEOID)
# Adding 0 to beginning of short ones
df_main$GEOID <- df_main$GEOID %>% str_trunc(11) %>% str_pad(11, "left", pad = "0")


```

